name: Deploy [PRE] Environment

on:
  push:
    branches:
      - relaese/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_PRE}}
          username: ${{ secrets.SERVER_USERNAME_PRE }}
          password: ${{ secrets.SERVER_PASSWORD_PRE }}
          source: './'
          target: /home/server-pre

      - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_PRE}}
          username: ${{ secrets.SERVER_USERNAME_PRE }}
          password: ${{ secrets.SERVER_PASSWORD_PRE }}
          script: |
            cd /home/server-pre
            node -v
            npm i pnpm -g
            pnpm install
            cd packages/frondend
            pnpm run build:h5:cd
            cd ../backend
            pnpm run build
            pnpm run pm2:pre
