name: Deploy [Test] Environment

on:
  push:
    branches:
      - release-**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_TEST }}
          username: ${{ secrets.SERVER_USERNAME_TEST }}
          password: ${{ secrets.SERVER_PASSWORD_TEST }}
          source: './'
          target: /home/server-test

      - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_TEST }}
          username: ${{ secrets.SERVER_USERNAME_TEST }}
          password: ${{ secrets.SERVER_PASSWORD_TEST }}
          script: |
            cd /home/server-test
            node -v
            npm i pnpm -g
            pnpm install
            cd packages/frondend
            pnpm run build:h5:cd
            cd ../backend
            pnpm run build
            pnpm run pm2:test
